<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

defineOptions({ name: 'AboutView' })

const scrolled = ref(false)

onMounted(() => {
  window.addEventListener('scroll', () => {
    scrolled.value = window.scrollY > 20
  })
})

onUnmounted(() => {
  window.removeEventListener('scroll', () => {})
})

function scrollToHome() {
  location.href = '/'
}
</script>

<template>
  <div class="about-page">
    <nav class="about-navbar" :class="{ scrolled: scrolled }">
      <div class="container navbar-inner">
        <button class="home-link" @click="scrollToHome">DV</button>
        <div class="nav-links">
          <a href="/" @click.prevent="scrollToHome">Home</a>
          <a href="/about" class="active">About Project</a>
        </div>
      </div>
    </nav>

    <main class="about-content">
      <section class="hero-section">
        <h1 class="title">About This Project</h1>
        <p class="subtitle">A live demonstration of what local AI can achieve</p>
      </section>

      <section class="section">
        <h2 class="section-title">The Goal</h2>
        <p>
          This portfolio landing page was entirely generated by local language models as an experiment
          to test their practical capabilities. Rather than using cloud-based APIs, every line of code,
          design decision, and content iteration was produced by AI running entirely on my own hardware.
        </p>
      </section>

      <section class="section">
        <h2 class="section-title">AI Tech Stack</h2>
        <div class="stack-grid">
          <div class="stack-card">
            <div class="stack-icon">🖥️</div>
            <h3>NVIDIA Spark on My Desk</h3>
            <p>The local inference engine powering all AI reasoning, running entirely on dedicated GPU hardware in my workspace.</p>
          </div>
          <div class="stack-card">
            <div class="stack-icon">🧠</div>
            <h3>Qwen 3.6 MoE</h3>
            <p>Mixture-of-Experts language model serving as the primary code generation and reasoning engine for this project.</p>
          </div>
          <div class="stack-card">
            <div class="stack-icon">⚡</div>
            <h3>Cursor IDE</h3>
            <p>The development environment where the AI agent writes, edits, and iterates on the codebase in real time.</p>
          </div>
        </div>
      </section>

      <section class="section">
        <h2 class="section-title">Agentic Tools</h2>
        <p>
          Beyond code generation, the AI agent was equipped with agentic tools that enabled it to
          interact with external data sources autonomously:
        </p>
        <div class="tools-list">
          <div class="tool-item">
            <span class="tool-badge">LinkedIn</span>
            <p>Queried my LinkedIn profile to extract professional experience, skills, and career history for the portfolio content.</p>
          </div>
          <div class="tool-item">
            <span class="tool-badge">Logseq</span>
            <p>Accessed my personal knowledge base in Logseq to pull in contextual information, notes, and background details.</p>
          </div>
        </div>
      </section>

      <section class="section">
        <h2 class="section-title">Why It Matters</h2>
        <p>
          This project proves that capable local AI models, combined with the right tooling, can
          independently produce polished, production-quality software without any cloud dependency.
          It is a proof-of-concept for fully self-contained AI-assisted development.
        </p>
      </section>
    </main>
  </div>
</template>

<style scoped>
.about-page {
  min-height: 100vh;
  background: var(--bg-primary);
  color: var(--text-primary);
}

.about-navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
  padding: 1.25rem 0;
  transition: all 0.3s ease;
  background: transparent;
}

.about-navbar.scrolled {
  background: rgba(10, 14, 23, 0.95);
  backdrop-filter: blur(10px);
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--border);
}

.navbar-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.home-link {
  font-size: 1.25rem;
  font-weight: 700;
  color: var(--accent);
  letter-spacing: 0.1em;
  background: none;
  border: none;
  cursor: pointer;
}

.nav-links {
  display: flex;
  gap: 2rem;
}

.nav-links a {
  color: var(--text-secondary);
  font-size: 0.875rem;
  font-weight: 500;
  letter-spacing: 0.02em;
  transition: color 0.2s;
  cursor: pointer;
  text-decoration: none;
}

.nav-links a:hover,
.nav-links a.active {
  color: var(--accent);
}

.about-content {
  padding-top: 80px;
}

.hero-section {
  text-align: center;
  padding: 5rem 0 3rem;
}

.title {
  font-size: 2.5rem;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 1rem;
}

.subtitle {
  font-size: 1.125rem;
  color: var(--text-secondary);
  max-width: 600px;
  margin: 0 auto;
}

.section {
  max-width: 800px;
  margin: 0 auto;
  padding: 2.5rem 1.5rem;
}

.section-title {
  font-size: 1.5rem;
  font-weight: 600;
  color: var(--accent);
  margin-bottom: 1.25rem;
}

.section p {
  color: var(--text-secondary);
  line-height: 1.75;
  font-size: 1rem;
}

.stack-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1.5rem;
  margin-top: 1.5rem;
}

.stack-card {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1.75rem;
  transition: border-color 0.2s;
}

.stack-card:hover {
  border-color: var(--accent);
}

.stack-icon {
  font-size: 2rem;
  margin-bottom: 1rem;
}

.stack-card h3 {
  font-size: 1.1rem;
  font-weight: 600;
  color: var(--text-primary);
  margin-bottom: 0.75rem;
}

.stack-card p {
  font-size: 0.875rem;
  color: var(--text-secondary);
  line-height: 1.6;
}

.tools-list {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  margin-top: 1.5rem;
}

.tool-item {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1.5rem;
}

.tool-badge {
  display: inline-block;
  background: color-mix(in srgb, var(--accent) 15%, transparent);
  color: var(--accent);
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.05em;
  padding: 0.25rem 0.75rem;
  border-radius: 999px;
  margin-bottom: 0.75rem;
}

.tool-item p {
  font-size: 0.9375rem;
}

@media (max-width: 768px) {
  .title {
    font-size: 1.75rem;
  }

  .hero-section {
    padding: 3rem 0 2rem;
  }

  .section {
    padding: 2rem 1.25rem;
  }

  .stack-grid {
    grid-template-columns: 1fr;
  }
}
</style>
